In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

iris = datasets.load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

binary_classifier = LogisticRegression(max_iter=200)

ovr_classifier = OneVsRestClassifier(binary_classifier)

ovr_classifier.fit(X_train, y_train)

y_pred = ovr_classifier.predict(X_test)

In [3]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of One-vs-Rest classifier: {accuracy * 100:.2f}%")


conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

print("\nPredictions vs Actual labels:")
for i in range(5):
    print(f"Predicted: {y_pred[i]}, Actual: {y_test[i]}")

Accuracy of One-vs-Rest classifier: 95.56%
Confusion Matrix:
[[16  0  0]
 [ 0 16  2]
 [ 0  0 11]]

Predictions vs Actual labels:
Predicted: 2, Actual: 2
Predicted: 1, Actual: 1
Predicted: 0, Actual: 0
Predicted: 2, Actual: 2
Predicted: 0, Actual: 0


In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsOneClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris

data = load_iris()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

log_reg = LogisticRegression(max_iter=200)
ovo_classifier = OneVsOneClassifier(log_reg)

ovo_classifier.fit(X_train, y_train)

y_pred = ovo_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

print("\nPredictions vs Actual labels:")
for i in range(5):
    print(f"Predicted: {y_pred[i]}, Actual: {y_test[i]}")


Accuracy: 1.00
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Predictions vs Actual labels:
Predicted: 1, Actual: 1
Predicted: 0, Actual: 0
Predicted: 2, Actual: 2
Predicted: 1, Actual: 1
Predicted: 1, Actual: 1
